In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("/Users/snip/Documents/MEOP/power_dependence_plots/fit_parameters_all_files.csv")
df

,filename,power,cell,datagrab,ic_range_min,ic_range_max,bu_range_min,bu_range_max,pl_range_min,pl_range_max,...,P0_err,tau,tau_err,c,c_err,t_offset_decay,t_offset_decay_err,dc_chi2,dc_ndf,dc_chi2_ndf
0,3W_C8_datagrab1,3W,C8,datagrab1,0.0,55.6,69.6,161.8,91.8,261.3,...,0.876196,109.164803,0.465850,4.050965,0.033963,295.920023,2.079323,137.107206,592,0.231600
1,3W_C8_datagrab2,3W,C8,datagrab2,0.0,76.2,88.2,118.8,123.8,390.5,...,0.822192,109.786302,0.506345,3.944150,0.040969,388.445772,2.032456,109.901377,506,0.217196
2,3W_C8_datagrab3,3W,C8,datagrab3,0.0,81.4,93.4,144.3,116.3,475.0,...,0.839253,110.120352,0.473929,3.988972,0.043378,476.617832,1.868920,113.161175,496,0.228148
3,3W_C9_datagrab1,3W,C9,datagrab1,0.0,75.1,87.1,150.2,155.2,379.2,...,0.907302,102.963639,0.479251,2.427855,0.057300,373.718502,1.723930,107.497653,413,0.260285
4,3W_C9_datagrab2,3W,C9,datagrab2,0.0,71.6,81.6,180.3,170.3,400.2,...,0.898544,102.873947,0.707673,2.446692,0.066505,421.014759,2.331256,95.365338,375,0.254308
5,3W_C9_datagrab3,3W,C9,datagrab3,0.0,33.1,45.1,116.9,136.9,415.0,...,0.857285,103.094420,0.586513,2.472990,0.070145,442.117925,1.842224,84.875988,357,0.237748
6,3W_C9_datagrab4,3W,C9,datagrab4,0.0,94.0,104.0,171.3,188.3,379.4,...,0.839571,103.045654,0.519737,2.463561,0.062672,422.073229,1.712162,84.552355,375,0.225473
7,4W_C8_datagrab1,4W,C8,datagrab1,0.0,141.2,153.2,184.4,210.4,488.9,...,0.914162,117.990797,0.558266,3.753618,0.044475,484.009015,2.278795,161.051744,554,0.290707
8,4W_C8_datagrab2,4W,C8,datagrab2,0.0,185.3,195.3,227.6,220.6,501.5,...,0.872397,116.691787,0.551400,3.822371,0.044393,502.693834,2.197556,141.720031,537,0.263911
9,4W_C8_datagrab3,4W,C8,datagrab3,0.0,197.1,207.1,238.3,234.3,515.7,...,0.951549,118.404952,0.638605,3.760431,0.052943,516.960823,2.434793,165.799849,514,0.322568
10,4W_C9_datagrab1,4W,C9,datagrab1,0.0,141.8,165.8,215.1,226.1,437.2,...,0.899324,98.252752,0.421085,2.495036,0.064214,431.883932,1.424655,90.717292,367,0.247186
11,4W_C9_datagrab2,4W,C9,datagrab2,0.0,116.8,128.8,169.0,186.0,352.4,...,0.902809,99.314633,0.432847,2.325872,0.055943,392.400976,1.587177,102.688674,405,0.253552
12,4W_C9_datagrab3,4W,C9,datagrab3,0.0,72.4,86.4,126.7,131.7,395.0,...,0.880967,98.343117,0.389969,2.500240,0.049086,428.816580,1.501653,100.228232,427,0.234727
13,5W_C8_datagrab1,5W,C8,datagrab1,0.0,54.3,67.3,100.1,123.1,355.9,...,0.889467,102.234785,0.515536,3.022877,0.062136,343.614750,1.760856,95.622983,385,0.248371
14,5W_C8_datagrab2,5W,C8,datagrab2,0.0,103.9,114.9,147.6,134.6,295.9,...,0.875755,102.226501,0.569528,3.011196,0.059574,337.351349,1.972989,94.077704,391,0.240608
15,5W_C8_datagrab3,5W,C8,datagrab3,0.0,108.3,122.3,202.9,138.9,347.1,...,0.853313,102.680379,0.489684,2.944459,0.058614,337.902727,1.682511,89.619863,391,0.229207
16,5W_C9_datagrab1,5W,C9,datagrab1,0.0,97.2,111.2,155.5,157.5,362.3,...,0.915199,103.489672,0.374076,2.980791,0.040902,375.398095,1.610919,137.835589,522,0.264053
17,5W_C9_datagrab2,5W,C9,datagrab2,0.0,75.1,89.1,131.4,133.4,379.3,...,0.808598,104.067763,0.354842,2.831373,0.039657,407.555318,1.454461,102.504209,493,0.207919
18,5W_C9_datagrab3,5W,C9,datagrab3,0.0,47.1,61.1,105.5,116.5,435.0,...,0.896477,103.952745,0.405586,2.853593,0.047350,435.659918,1.599477,118.486487,468,0.253176
19,6W_C8_datagrab1,6W,C8,datagrab1,0.0,137.6,165.6,202.1,180.1,365.4,...,0.893317,101.230814,0.600558,2.965835,0.070964,374.353490,1.909346,88.419332,355,0.249069
20,6W_C8_datagrab2,6W,C8,datagrab2,0.0,121.1,133.1,163.7,150.7,365.0,...,0.852414,101.588475,0.517825,2.895121,0.063999,362.003753,1.697132,83.725638,368,0.227515
21,6W_C8_datagrab3,6W,C8,datagrab3,0.0,119.9,128.9,184.8,189.8,368.3,...,0.865485,101.210442,0.570903,2.859894,0.066728,368.202567,1.841020,83.760069,360,0.232667
22,6W_C9_datagrab1,6W,C9,datagrab1,0.0,65.7,79.7,129.9,119.9,285.9,...,0.855110,102.123188,0.425796,2.714698,0.061701,328.640786,1.432533,87.913938,379,0.231963
23,6W_C9_datagrab2,6W,C9,datagrab2,0.0,61.7,77.7,126.4,122.4,343.7,...,0.908389,102.398210,0.431763,2.808101,0.070289,341.394169,1.397768,96.727805,366,0.264284
24,6W_C9_datagrab3,6W,C9,datagrab3,0.0,43.1,59.1,92.8,100.8,327.6,...,0.910917,101.065163,0.459509,2.944236,0.068900,343.139722,1.505696,95.123816,365,0.260613
25,7W_C8_datagrab1,7W,C8,datagrab1,0.0,81.6,95.6,132.2,113.2,385.6,...,0.870007,90.961006,0.441625,3.355167,0.046494,385.454996,1.719869,82.059763,401,0.204638
26,7W_C8_datagrab2,7W,C8,datagrab2,0.0,74.6,88.6,142.0,105.0,438.4,...,0.784691,89.552726,0.332516,3.438614,0.038293,426.426525,1.358096,69.442011,421,0.164945
27,7W_C8_datagrab3,7W,C8,datagrab3,0.0,78.9,94.9,126.6,104.6,429.0,...,0.856414,90.305653,0.362029,3.364515,0.041181,420.203122,1.486939,84.270441,428,0.196894
28,7W_C9_datagrab1,7W,C9,datagrab1,0.0,58.5,71.5,101.7,106.7,276.0,...,0.845433,90.373320,0.331697,3.045445,0.056272,312.682486,1.163502,69.960511,351,0.199318
29,7W_C9_datagrab2,7W,C9,datagrab2,0.0,66.8,82.8,112.9,114.9,363.4,...,0.814047,89.584473,0.351447,3.126968,0.052371,373.079552,1.253529,64.318155,354,0.181690
30,7W_C9_datagrab3,7W,C9,datagrab3,0.0,94.5,105.5,136.6,138.6,332.7,...,0.841133,91.509168,0.346460,3.251749,0.050101,344.859845,1.286599,75.780825,381,0.198900
31,8W_C8_datagrab1,8W,C8,datagrab1,0.0,178.1,190.1,261.4,200.4,417.4,...,0.862227,99.730421,0.510163,3.328504,0.048765,422.616806,1.938791,95.370718,426,0.223875
32,8W_C8_datagrab2,8W,C8,datagrab2,0.0,137.0,149.0,227.5,163.5,417.8,...,0.918745,100.565960,0.458509,3.307703,0.049438,405.456636,1.785221,112.073707,442,0.253560
33,8W_C8_datagrab3,8W,C8,datagrab3,0.0,138.9,150.9,231.5,191.5,400.6,...,0.865066,100.809656,0.438078,3.277020,0.044595,391.061019,1.739434,101.784317,455,0.223702
34,8W_C9_datagrab1,8W,C9,datagrab1,0.0,137.2,148.2,181.9,186.9,388.5,...,0.856371,103.372243,0.392356,3.048777,0.052619,427.774719,1.437884,98.830931,422,0.234197
35,8W_C9_datagrab2,8W,C9,datagrab2,0.0,84.2,95.2,156.3,137.3,387.3,...,0.895592,102.111826,0.368981,3.188665,0.047526,390.801887,1.459343,114.808133,457,0.251221
36,8W_C9_datagrab3,8W,C9,datagrab3,0.0,103.5,117.5,149.0,154.0,379.3,...,0.880726,101.744778,0.364831,3.187358,0.045691,386.050175,1.454994,111.236272,462,0.240771

In [ ]:

import re
def extract_integer(s):
    numeric_string= "".join(c for c in s if c.isdigit())
    print(numeric_string)
    return int(numeric_string) if numeric_string else 0

In [ ]:
df_C8 = df[df["cell"]=="C8"]
df_C8["power_int"]= df_C8["power"].apply(extract_integer)

3
3
3
4
4
4
5
5
5
6
6
6
7
7
7
8
8
8

/var/folders/gd/9mz33tj93gxcvrr1gtyl314w0000gn/T/ipykernel_25824/518199892.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_C8["power_int"]= df_C8["power"].apply(extract_integer)

,filename,power,cell,datagrab,ic_range_min,ic_range_max,bu_range_min,bu_range_max,pl_range_min,pl_range_max,...,tau,tau_err,c,c_err,t_offset_decay,t_offset_decay_err,dc_chi2,dc_ndf,dc_chi2_ndf,power_int
0,3W_C8_datagrab1,3W,C8,datagrab1,0.0,55.6,69.6,161.8,91.8,261.3,...,109.164803,0.465850,4.050965,0.033963,295.920023,2.079323,137.107206,592,0.231600,3
1,3W_C8_datagrab2,3W,C8,datagrab2,0.0,76.2,88.2,118.8,123.8,390.5,...,109.786302,0.506345,3.944150,0.040969,388.445772,2.032456,109.901377,506,0.217196,3
2,3W_C8_datagrab3,3W,C8,datagrab3,0.0,81.4,93.4,144.3,116.3,475.0,...,110.120352,0.473929,3.988972,0.043378,476.617832,1.868920,113.161175,496,0.228148,3
7,4W_C8_datagrab1,4W,C8,datagrab1,0.0,141.2,153.2,184.4,210.4,488.9,...,117.990797,0.558266,3.753618,0.044475,484.009015,2.278795,161.051744,554,0.290707,4
8,4W_C8_datagrab2,4W,C8,datagrab2,0.0,185.3,195.3,227.6,220.6,501.5,...,116.691787,0.551400,3.822371,0.044393,502.693834,2.197556,141.720031,537,0.263911,4
9,4W_C8_datagrab3,4W,C8,datagrab3,0.0,197.1,207.1,238.3,234.3,515.7,...,118.404952,0.638605,3.760431,0.052943,516.960823,2.434793,165.799849,514,0.322568,4
13,5W_C8_datagrab1,5W,C8,datagrab1,0.0,54.3,67.3,100.1,123.1,355.9,...,102.234785,0.515536,3.022877,0.062136,343.614750,1.760856,95.622983,385,0.248371,5
14,5W_C8_datagrab2,5W,C8,datagrab2,0.0,103.9,114.9,147.6,134.6,295.9,...,102.226501,0.569528,3.011196,0.059574,337.351349,1.972989,94.077704,391,0.240608,5
15,5W_C8_datagrab3,5W,C8,datagrab3,0.0,108.3,122.3,202.9,138.9,347.1,...,102.680379,0.489684,2.944459,0.058614,337.902727,1.682511,89.619863,391,0.229207,5
19,6W_C8_datagrab1,6W,C8,datagrab1,0.0,137.6,165.6,202.1,180.1,365.4,...,101.230814,0.600558,2.965835,0.070964,374.353490,1.909346,88.419332,355,0.249069,6
20,6W_C8_datagrab2,6W,C8,datagrab2,0.0,121.1,133.1,163.7,150.7,365.0,...,101.588475,0.517825,2.895121,0.063999,362.003753,1.697132,83.725638,368,0.227515,6
21,6W_C8_datagrab3,6W,C8,datagrab3,0.0,119.9,128.9,184.8,189.8,368.3,...,101.210442,0.570903,2.859894,0.066728,368.202567,1.841020,83.760069,360,0.232667,6
25,7W_C8_datagrab1,7W,C8,datagrab1,0.0,81.6,95.6,132.2,113.2,385.6,...,90.961006,0.441625,3.355167,0.046494,385.454996,1.719869,82.059763,401,0.204638,7
26,7W_C8_datagrab2,7W,C8,datagrab2,0.0,74.6,88.6,142.0,105.0,438.4,...,89.552726,0.332516,3.438614,0.038293,426.426525,1.358096,69.442011,421,0.164945,7
27,7W_C8_datagrab3,7W,C8,datagrab3,0.0,78.9,94.9,126.6,104.6,429.0,...,90.305653,0.362029,3.364515,0.041181,420.203122,1.486939,84.270441,428,0.196894,7
31,8W_C8_datagrab1,8W,C8,datagrab1,0.0,178.1,190.1,261.4,200.4,417.4,...,99.730421,0.510163,3.328504,0.048765,422.616806,1.938791,95.370718,426,0.223875,8
32,8W_C8_datagrab2,8W,C8,datagrab2,0.0,137.0,149.0,227.5,163.5,417.8,...,100.565960,0.458509,3.307703,0.049438,405.456636,1.785221,112.073707,442,0.253560,8
33,8W_C8_datagrab3,8W,C8,datagrab3,0.0,138.9,150.9,231.5,191.5,400.6,...,100.809656,0.438078,3.277020,0.044595,391.061019,1.739434,101.784317,455,0.223702,8

In [37]:
df_C8_mean=df_C8["power_int"].groupby("power_int").mean()
df_C8_mean

KeyError: 'power_int'